version: '3.7'

services:
    api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        ports:
            - 8888:80
    mq:
        ports:
            - 5672:5672
            - 15672:15672