version: '3.7'

services:
  api:
    image: service.api
    container_name: service.api
    depends_on:
      - mq
    build:
      context: .
      dockerfile: src/FSharp.OpenTTD.Service/Dockerfile
    networks:
      - openttd
  
  mq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - openttd
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 10s
      timeout: 10s
      retries: 5
networks:
  openttd:
    name: openttd.network
