version: '3.7'

services:
  api:
    image: service.api
    container_name: service.api
    restart: on-failure
    depends_on:
      - mq
    links:
      - mq
    build:
      context: .
      dockerfile: src/FSharp.OpenTTD.Service/Dockerfile
    networks:
      - openttd
  
  mq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - openttd
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 5s
      timeout: 10s
      retries: 5
networks:
  openttd:
    name: openttd.network
