version: '2.1'

services:
  api:
    image: service.api
    container_name: service.api
    restart: always
    depends_on:
      mq:
        condition: service_healthy
    build:
      context: .
      dockerfile: src/FSharp.OpenTTD.Service/Dockerfile
    networks:
      - openttd
  
  mq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - openttd
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 20s
      retries: 5
networks:
  openttd:
    name: openttd.network
